// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UIWwi_v9A2PrTyJifieUldTd2l_lZj0',
    appId: '1:332003769970:web:e1a29206b4716b48b20ceb',
    messagingSenderId: '332003769970',
    projectId: 'chatapp-ecda3',
    authDomain: 'chatapp-ecda3.firebaseapp.com',
    storageBucket: 'chatapp-ecda3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYYVjLdGeQIndcS2qmLrapFsc-ImOebFs',
    appId: '1:332003769970:android:9b304f71ff0bf321b20ceb',
    messagingSenderId: '332003769970',
    projectId: 'chatapp-ecda3',
    storageBucket: 'chatapp-ecda3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2jcFWocI9uJWc-Dvc0ZtQHY6fdyIKRY',
    appId: '1:332003769970:ios:8fb692ea721d1e58b20ceb',
    messagingSenderId: '332003769970',
    projectId: 'chatapp-ecda3',
    storageBucket: 'chatapp-ecda3.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe2jcFWocI9uJWc-Dvc0ZtQHY6fdyIKRY',
    appId: '1:332003769970:ios:8fb692ea721d1e58b20ceb',
    messagingSenderId: '332003769970',
    projectId: 'chatapp-ecda3',
    storageBucket: 'chatapp-ecda3.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2UIWwi_v9A2PrTyJifieUldTd2l_lZj0',
    appId: '1:332003769970:web:3c3fcbc6d0e71245b20ceb',
    messagingSenderId: '332003769970',
    projectId: 'chatapp-ecda3',
    authDomain: 'chatapp-ecda3.firebaseapp.com',
    storageBucket: 'chatapp-ecda3.appspot.com',
  );
}
